{"describe": "希望让人自由。", "name": "肖申克的救赎", "director_and_player": ["\n                            导演: 弗兰克·德拉邦特 Frank Darabont   主演: 蒂姆·罗宾斯 Tim Robbins /...", "\n                            1994 / 美国 / 犯罪 剧情\n                        "]}
{"describe": "怪蜀黍和小萝莉不得不说的故事。", "name": "这个杀手不太冷", "director_and_player": ["\n                            导演: 吕克·贝松 Luc Besson   主演: 让·雷诺 Jean Reno / 娜塔丽·波特曼 ...", "\n                            1994 / 法国 / 剧情 动作 犯罪\n                        "]}
{"describe": "风华绝代。", "name": "霸王别姬", "director_and_player": ["\n                            导演: 陈凯歌 Kaige Chen   主演: 张国荣 Leslie Cheung / 张丰毅 Fengyi Zha...", "\n                            1993 / 中国大陆 香港 / 剧情 爱情 同性\n                        "]}
{"describe": "一部美国近现代史。", "name": "阿甘正传", "director_and_player": ["\n                            导演: Robert Zemeckis   主演: Tom Hanks / Robin Wright Penn / Gary Sinise", "\n                            1994 / 美国 / 剧情 爱情\n                        "]}
{"describe": "最美的谎言。", "name": "美丽人生", "director_and_player": ["\n                            导演: 罗伯托·贝尼尼 Roberto Benigni   主演: 罗伯托·贝尼尼 Roberto Beni...", "\n                            1997 / 意大利 / 剧情 喜剧 爱情 战争\n                        "]}
{"describe": "最好的宫崎骏，最好的久石让。 ", "name": "千与千寻", "director_and_player": ["\n                            导演: 宫崎骏 Hayao Miyazaki   主演: 柊瑠美 Rumi Hîragi / 入野自由 Miy...", "\n                            2001 / 日本 / 剧情 动画 奇幻\n                        "]}
{"describe": "拯救一个人，就是拯救整个世界。", "name": "辛德勒的名单", "director_and_player": ["\n                            导演: 史蒂文·斯皮尔伯格 Steven Spielberg   主演: 连姆·尼森 Liam Neeson...", "\n                            1993 / 美国 / 剧情 历史 战争\n                        "]}
{"describe": "失去的才是永恒的。 ", "name": "泰坦尼克号", "director_and_player": ["\n                            导演: 詹姆斯·卡梅隆 James Cameron   主演: 莱昂纳多·迪卡普里奥 Leonardo...", "\n                            1997 / 美国 / 剧情 爱情 灾难\n                        "]}
{"describe": "诺兰给了我们一场无法盗取的梦。", "name": "盗梦空间", "director_and_player": ["\n                            导演: 克里斯托弗·诺兰 Christopher Nolan   主演: 莱昂纳多·迪卡普里奥 Le...", "\n                            2010 / 美国 英国 / 剧情 动作 科幻 悬疑 冒险\n                        "]}
{"describe": "小瓦力，大人生。", "name": "机器人总动员", "director_and_player": ["\n                            导演: 安德鲁·斯坦顿 Andrew Stanton   主演: 本·贝尔特 Ben Burtt / 艾丽...", "\n                            2008 / 美国 / 喜剧 爱情 科幻 动画 冒险\n                        "]}
{"describe": "每个人都要走一条自己坚定了的路，就算是粉身碎骨。 ", "name": "海上钢琴师", "director_and_player": ["\n                            导演: 朱塞佩·托纳多雷 Giuseppe Tornatore   主演: 蒂姆·罗斯 Tim Roth / ...", "\n                            1998 / 意大利 / 剧情 音乐\n                        "]}
{"describe": "英俊版憨豆，高情商版谢耳朵。", "name": "三傻大闹宝莱坞", "director_and_player": ["\n                            导演: 拉库马·希拉尼 Rajkumar Hirani   主演: 阿米尔·汗 Aamir Khan / 卡...", "\n                            2009 / 印度 / 剧情 喜剧 爱情 歌舞\n                        "]}
{"describe": "永远都不能忘记你所爱的人。", "name": "忠犬八公的故事", "director_and_player": ["\n                            导演: 莱塞·霍尔斯道姆 Lasse Hallström   主演: 理查·基尔 Richard Ger...", "\n                            2009 / 美国 英国 / 剧情\n                        "]}
{"describe": "天籁一般的童声，是最接近上帝的存在。 ", "name": "放牛班的春天", "director_and_player": ["\n                            导演: 克里斯托夫·巴拉蒂 Christophe Barratier   主演: 杰拉尔·朱诺 Géra...", "\n                            2004 / 法国 瑞士 德国 / 剧情 音乐\n                        "]}
{"describe": "一生所爱。", "name": "大话西游之大圣娶亲", "director_and_player": ["\n                            导演: 刘镇伟 Jeffrey Lau   主演: 周星驰 Stephen Chow / 吴孟达 Man Tat Ng...", "\n                            2017 / 香港 中国大陆 / 动作 冒险 喜剧 奇幻 爱情\n                        "]}
{"describe": "千万不要记恨你的对手，这样会让你失去理智。", "name": "教父", "director_and_player": ["\n                            导演: 弗朗西斯·福特·科波拉 Francis Ford Coppola   主演: 马龙·白兰度 M...", "\n                            1972 / 美国 / 剧情 犯罪\n                        "]}
{"describe": "人人心中都有个龙猫，童年就永远不会消失。", "name": "龙猫", "director_and_player": ["\n                            导演: 宫崎骏 Hayao Miyazaki   主演: 日高法子 Noriko Hidaka / 坂本千夏 Ch...", "\n                            1988 / 日本 / 动画 奇幻\n                        "]}
{"describe": "如果再也不能见到你，祝你早安，午安，晚安。", "name": "楚门的世界", "director_and_player": ["\n                            导演: 彼得·威尔 Peter Weir   主演: 金·凯瑞 Jim Carrey / 劳拉·琳妮 Lau...", "\n                            1998 / 美国 / 剧情 科幻\n                        "]}
{"describe": "Tomorrow is another day.", "name": "乱世佳人", "director_and_player": ["\n                            导演: Victor Fleming / George Cukor   主演: 克拉克·盖博 Clark Gable / ...", "\n                            1939 / 美国 / 剧情 爱情 战争\n                        "]}
{"describe": "那些吻戏，那些青春，都在影院的黑暗里被泪水冲刷得无比清晰。", "name": "天堂电影院", "director_and_player": ["\n                            导演: 朱塞佩·托纳多雷 Giuseppe Tornatore   主演: 安东娜拉·塔莉 Antonel...", "\n                            1988 / 意大利 法国 / 剧情 爱情\n                        "]}
{"describe": "平民励志片。 ", "name": "当幸福来敲门", "director_and_player": ["\n                            导演: 加布里尔·穆奇诺 Gabriele Muccino   主演: 威尔·史密斯 Will Smith ...", "\n                            2006 / 美国 / 剧情 传记 家庭\n                        "]}
{"describe": "满满温情的高雅喜剧。", "name": "触不可及", "director_and_player": ["\n                            导演: 奥利维·那卡什 Olivier Nakache / 艾力克·托兰达 Eric Toledano   主...", "\n                            2011 / 法国 / 剧情 喜剧\n                        "]}
{"describe": "邪恶与平庸蛰伏于同一个母体，在特定的时间互相对峙。", "name": "搏击俱乐部", "director_and_player": ["\n                            导演: 大卫·芬奇 David Fincher   主演: 爱德华·诺顿 Edward Norton / 布拉...", "\n                            1999 / 美国 德国 / 剧情 动作 悬疑 惊悚\n                        "]}
{"describe": "1957年的理想主义。 ", "name": "十二怒汉", "director_and_player": ["\n                            导演: Sidney Lumet   主演: 亨利·方达 Henry Fonda / 马丁·鲍尔萨姆 Marti...", "\n                            1957 / 美国 / 剧情\n                        "]}
{"describe": "香港电影史上永不过时的杰作。", "name": "无间道", "director_and_player": ["\n                            导演: 刘伟强 / 麦兆辉   主演: 刘德华 / 梁朝伟 / 黄秋生", "\n                            2002 / 香港 / 犯罪 悬疑 惊悚\n                        "]}
{"describe": "人与自然的战争史诗。", "name": "幽灵公主", "director_and_player": ["\n                            导演: 宫崎骏   主演: 松田洋治 / 石田百合子 / 田中裕子", "\n                            1997 / 日本 / 动画 冒险 奇幻\n                        "]}
{"describe": "深入内心的恐怖，出人意料的结局。", "name": "第六感", "director_and_player": ["\n                            导演: M·奈特·沙马兰 M. Night Shyamalan   主演: 布鲁斯·威利斯 Bruce Wi...", "\n                            1999 / 美国 / 剧情 悬疑 恐怖\n                        "]}
{"describe": "一场华丽的意淫。", "name": "阳光灿烂的日子", "director_and_player": ["\n                            导演: 姜文 Wen Jiang   主演: 夏雨 Yu Xia / 宁静 Jing Ning / 陶虹 Hong Tao", "\n                            1994 / 中国大陆 香港 / 剧情\n                        "]}
{"describe": "你给我翻译翻译，神马叫做TMD的惊喜。", "name": "让子弹飞", "director_and_player": ["\n                            导演: 姜文 Wen Jiang   主演: 姜文 Wen Jiang / 葛优 You Ge / 周润发 Yun-F...", "\n                            2010 / 中国大陆 香港 / 剧情 喜剧 动作 西部\n                        "]}
{"describe": "爱情纠缠，男女一致。", "name": "春光乍泄", "director_and_player": ["\n                            导演: 王家卫   主演: 张国荣 / 梁朝伟 / 张震", "\n                            1997 / 香港 日本 韩国 / 剧情 爱情 同性\n                        "]}
{"describe": "抱着梦想而活着的人是幸福的，怀抱梦想而死去的人是不朽的。", "name": "大鱼", "director_and_player": ["\n                            导演: Tim Burton   主演: Ewan McGregor / Albert Finney / Billy Crudup", "\n                            2003 / 美国 / 剧情 家庭 奇幻 冒险\n                        "]}
{"describe": "经典之作，历久弥新。", "name": "大闹天宫", "director_and_player": ["\n                            导演: 万籁鸣 Laiming Wan / 唐澄 Cheng  Tang   主演: 邱岳峰 Yuefeng Qiu /...", "\n                            1961(上集) / 1964(下集) / 1978(全本) / 2004(纪念版) / 中国大陆 / 动画 奇幻\n                        "]}
{"describe": "百看不厌。 ", "name": "射雕英雄传之东成西就", "director_and_player": ["\n                            导演: 刘镇伟 Jeffrey Lau   主演: 梁朝伟 Tony Leung Chiu Wai / 林青霞 Bri...", "\n                            1993 / 香港 / 喜剧 古装\n                        "]}
{"describe": "当一个死水般的体制内出现一个活跃的变数时，所有的腐臭都站在了光明的对面。", "name": "死亡诗社", "director_and_player": ["\n                            导演: 彼得·威尔 Peter Weir   主演: 罗宾·威廉姆斯 Robin Williams / 罗伯...", "\n                            1989 / 美国 / 剧情\n                        "]}
{"describe": "往事如烟，无处祭奠。", "name": "美国往事", "director_and_player": ["\n                            导演: Sergio Leone   主演: 罗伯特·德尼罗 Robert De Niro / 詹姆斯·伍兹 ...", "\n                            1984 / 意大利 美国 / 犯罪 剧情\n                        "]}
{"describe": "警察抓小偷，老鼠玩死猫。", "name": "七宗罪", "director_and_player": ["\n                            导演: 大卫·芬奇 David Fincher   主演: 摩根·弗里曼 Morgan Freeman / 布...", "\n                            1995 / 美国 / 剧情 犯罪 悬疑 惊悚\n                        "]}
{"describe": "史诗的终章。", "name": "指环王3：王者无敌", "director_and_player": ["\n                            导演: 彼得·杰克逊 Peter Jackson   主演: 维果·莫腾森 Viggo Mortensen / ...", "\n                            2003 / 美国 新西兰 / 剧情 动作 奇幻 冒险\n                        "]}
{"describe": "寂寞没有期限。", "name": "重庆森林", "director_and_player": ["\n                            导演: 王家卫 Kar Wai Wong   主演: 林青霞 Brigitte Lin / 金城武 Takeshi K...", "\n                            1994 / 香港 / 剧情 爱情\n                        "]}
{"describe": "再多各自牛逼的时光，也比不上一起傻逼的岁月。 ", "name": "阳光姐妹淘", "director_and_player": ["\n                            导演: 姜炯哲 Hyeong-Cheol Kang   主演: 沈恩京 Eun-kyung Shim / 闵孝琳 Hy...", "\n                            2011 / 韩国 / 剧情 喜剧\n                        "]}
{"describe": "被上帝抛弃了的上帝之城。", "name": "上帝之城", "director_and_player": ["\n                            导演: Kátia Lund / Fernando Meirelles   主演: Alexandre Rodrigues / Lea...", "\n                            2002 / 巴西 法国 / 犯罪 剧情\n                        "]}
{"describe": "昔日翩翩少年，今日大腹便便。", "name": "禁闭岛", "director_and_player": ["\n                            导演: Martin Scorsese   主演: 莱昂纳多·迪卡普里奥 Leonardo DiCaprio / ...", "\n                            2010 / 美国 / 剧情 悬疑 惊悚\n                        "]}
{"describe": "相逢只要一瞬间，等待却像是一辈子。", "name": "甜蜜蜜", "director_and_player": ["\n                            导演: 陈可辛 Peter Chan   主演: 黎明 Leon Lai / 张曼玉 Maggie Cheung / ...", "\n                            1996 / 香港 / 剧情 爱情\n                        "]}
{"describe": "音乐能化解仇恨。", "name": "钢琴家", "director_and_player": ["\n                            导演: 罗曼·波兰斯基 Roman Polanski   主演: 艾德里安·布洛迪 Adrien Brod...", "\n                            2002 / 法国 德国 英国 波兰 / 剧情 传记 历史 战争\n                        "]}
{"describe": "动物版《哈姆雷特》。", "name": "狮子王", "director_and_player": ["\n                            导演: Roger Allers / 罗伯·明可夫 Rob Minkoff   主演: 乔纳森·泰勒·托马...", "\n                            1994 / 美国 / 剧情 动画 冒险 歌舞 家庭\n                        "]}
{"describe": "史诗大片的典范。", "name": "勇敢的心", "director_and_player": ["\n                            导演: 梅尔·吉布森 Mel Gibson   主演: 梅尔·吉布森 Mel Gibson / 苏菲·玛...", "\n                            1995 / 美国 / 动作 传记 剧情 历史 战争\n                        "]}
{"describe": "以戏谑来戏谑戏谑。", "name": "被嫌弃的松子的一生", "director_and_player": ["\n                            导演: 中岛哲也 Tetsuya Nakashima   主演: 中谷美纪 Miki Nakatani / 瑛太 E...", "\n                            2006 / 日本 / 剧情 歌舞\n                        "]}
{"describe": "孪生蝙蝠侠大战克隆金刚狼。", "name": "致命魔术", "director_and_player": ["\n                            导演: 克里斯托弗·诺兰 Christopher Nolan   主演: 克里斯蒂安·贝尔 Christ...", "\n                            2006 / 美国 英国 / 剧情 悬疑 惊悚\n                        "]}
{"describe": "电影的现实意义大过电影本身。", "name": "辩护人", "director_and_player": ["\n                            导演: 杨宇硕 Woo-seok Yang   主演: 宋康昊 Kang-ho Song / 吴达洙 Dal-su O...", "\n                            2013 / 韩国 / 剧情\n                        "]}
{"describe": "我们一路奋战不是为了改变世界，而是为了不让世界改变我们。", "name": "熔炉", "director_and_player": ["\n                            导演: 黄东赫 Dong-hyuk Hwang   主演: 孔侑 Yoo Gong / 郑有美 Yu-mi Jeong ...", "\n                            2011 / 韩国 / 剧情\n                        "]}
{"describe": "真正的幸福是来自内心深处。", "name": "怦然心动", "director_and_player": ["\n                            导演: 罗伯·莱纳 Rob Reiner   主演: 玛德琳·卡罗尔 Madeline Carroll / 卡...", "\n                            2010 / 美国 / 剧情 喜剧 爱情\n                        "]}
{"describe": "爱情哪怕只有一天。", "name": "罗马假日", "director_and_player": ["\n                            导演: 威廉·惠勒 William Wyler   主演: 奥黛丽·赫本 Audrey Hepburn / 格...", "\n                            1953 / 美国 / 喜剧 剧情 爱情\n                        "]}
{"describe": "对天空的追逐，永不停止。 ", "name": "天空之城", "director_and_player": ["\n                            导演: 宫崎骏 Hayao Miyazaki   主演: 田中真弓 Mayumi Tanaka / 鹫尾真知子 ...", "\n                            1986 / 日本 / 动画 奇幻 冒险\n                        "]}
{"describe": "瑰丽壮观、无人能及的冒险之旅。", "name": "少年派的奇幻漂流", "director_and_player": ["\n                            导演: 李安 Ang Lee   主演: 苏拉·沙玛 Suraj Sharma / 拉菲·斯波 Rafe Spa...", "\n                            2012 / 美国 台湾 英国 加拿大 / 剧情 奇幻 冒险\n                        "]}
{"describe": "最不可能的那个人永远是最可能的。", "name": "致命ID", "director_and_player": ["\n                            导演: James Mangold   主演: John Cusack / Ray Liotta / Amanda Peet", "\n                            2003 / 美国 / 剧情 悬疑 惊悚\n                        "]}
{"describe": "没有一人完全善，也没有一人完全恶。", "name": "告白", "director_and_player": ["\n                            导演: 中岛哲也 Tetsuya Nakashima   主演: 松隆子 Takako Matsu / 冈田将生 ...", "\n                            2010 / 日本 / 剧情 惊悚\n                        "]}
{"describe": "我们都曾经是一一。", "name": "一一", "director_and_player": ["\n                            导演: 杨德昌   主演: 吴念真 / 李凯莉 Kelly Lee / 金燕玲 Elaine Jin", "\n                            2000 / 台湾 日本 / 剧情 爱情 家庭\n                        "]}
{"describe": "约翰尼·德普的独角戏。", "name": "加勒比海盗", "director_and_player": ["\n                            导演: 戈尔·维宾斯基 Gore Verbinski   主演: 约翰尼·德普 Johnny Depp / ...", "\n                            2003 / 美国 / 动作 冒险 奇幻\n                        "]}
{"describe": "缘分是个连绵词，最美不过一瞬。", "name": "爱在黎明破晓前", "director_and_player": ["\n                            导演: 理查德·林克莱特 Richard Linklater   主演: 伊桑·霍克 Ethan Hawke ...", "\n                            1995 / 美国 奥地利 瑞士 / 剧情 爱情\n                        "]}
{"describe": "浪漫忧郁的成人童话。", "name": "剪刀手爱德华", "director_and_player": ["\n                            导演: Tim Burton   主演: 约翰尼·德普 Johnny Depp / 薇诺娜·瑞德 Winona ...", "\n                            1990 / 美国 / 剧情 奇幻 爱情\n                        "]}
{"describe": "奔跑的孩子是天使。", "name": "小鞋子", "director_and_player": ["\n                            导演: 马基德·马基迪 Majid Majidi   主演: Amir Farrokh Hashemian / 默罕...", "\n                            1999 / 伊朗 / 剧情 家庭 儿童\n                        "]}
{"describe": "用音乐化解仇恨，让歌声串起美好。", "name": "音乐之声", "director_and_player": ["\n                            导演: Robert Wise   主演: 朱丽·安德鲁斯 Julie Andrews / 克里斯托弗·普...", "\n                            1965 / 美国 / 剧情 爱情 歌舞 家庭 传记\n                        "]}
{"describe": "比利·怀德满分作品。", "name": "控方证人", "director_and_player": ["\n                            导演: 比利·怀尔德 Billy Wilder   主演: 查尔斯·劳顿 Charles Laughton / ...", "\n                            1957 / 美国 / 剧情 犯罪 悬疑\n                        "]}
{"describe": "人生不能像做菜，把所有的料都准备好了才下锅。", "name": "饮食男女", "director_and_player": ["\n                            导演: 李安 Ang Lee   主演: 吴倩莲 Chien-lien Wu / 杨贵媚 Kuei-Mei Yang /...", "\n                            1994 / 台湾 美国 / 剧情 家庭\n                        "]}
{"describe": "故事的高级讲法。", "name": "低俗小说", "director_and_player": ["\n                            导演: 昆汀·塔伦蒂诺 Quentin Tarantino   主演: 约翰·特拉沃尔塔 John Tra...", "\n                            1994 / 美国 / 剧情 喜剧 犯罪\n                        "]}
{"describe": "旷古烁今。", "name": "大话西游之月光宝盒", "director_and_player": ["\n                            导演: 刘镇伟 Jeffrey Lau   主演: 周星驰 Stephen Chow / 吴孟达 Man Tat Ng...", "\n                            1995 / 香港 中国大陆 / 喜剧 动作 爱情 奇幻 冒险 古装\n                        "]}
{"describe": "对敌人的仁慈，就是对自己残忍。", "name": "鬼子来了", "director_and_player": ["\n                            导演: 姜文 Wen Jiang   主演: 姜文 Wen Jiang / 香川照之 Teruyuki Kagawa /...", "\n                            2000 / 中国大陆 / 剧情 战争\n                        "]}
{"describe": "4个臭皮匠顶个诸葛亮，盖·里奇果然不是盖的。", "name": "两杆大烟枪", "director_and_player": ["\n                            导演: Guy Ritchie   主演: Jason Flemyng / Dexter Fletcher / Nick Moran", "\n                            1998 / 英国 / 剧情 喜剧 犯罪\n                        "]}
{"describe": "无尽的黑暗。", "name": "蝙蝠侠：黑暗骑士", "director_and_player": ["\n                            导演: 克里斯托弗·诺兰 Christopher Nolan   主演: 克里斯蒂安·贝尔 Christ...", "\n                            2008 / 美国 英国 / 剧情 动作 科幻 犯罪 惊悚\n                        "]}
{"describe": "最后那些最无聊的事情，才是最值得怀念的。 ", "name": "飞屋环游记", "director_and_player": ["\n                            导演: 彼特·道格特 Pete Docter   主演: 爱德华·阿斯纳 Edward Asner / 克...", "\n                            2009 / 美国 / 剧情 喜剧 动画 奇幻 冒险\n                        "]}
{"describe": "绝对意义上的美轮美奂。", "name": "阿凡达", "director_and_player": ["\n                            导演: 詹姆斯·卡梅隆 James Cameron   主演: 萨姆·沃辛顿 Sam Worthington ...", "\n                            2009 / 美国 英国 / 动作 冒险 奇幻 科幻\n                        "]}
{"describe": "人言可畏。", "name": "狩猎", "director_and_player": ["\n                            导演: 托马斯·温特伯格 Thomas Vinterberg   主演: 麦斯·米科尔森 Mads Mik...", "\n                            2012 / 丹麦 瑞典 / 剧情\n                        "]}
{"describe": "小清新的故事里注入了大历史的情怀。", "name": "布达佩斯大饭店", "director_and_player": ["\n                            导演: 韦斯·安德森 Wes Anderson   主演: 拉尔夫·费因斯 Ralph Fiennes / ...", "\n                            2014 / 美国 德国 英国 / 剧情 喜剧\n                        "]}
{"describe": "动画片的圣经。", "name": "风之谷", "director_and_player": ["\n                            导演: 宫崎骏 Hayao Miyazaki   主演: 岛本须美 Sumi Shimamoto / 京田尚子 H...", "\n                            1984 / 日本 / 科幻 动画 奇幻 冒险\n                        "]}
{"describe": "每个人心中都有一座断背山。", "name": "断背山", "director_and_player": ["\n                            导演: 李安 Ang Lee   主演: 希斯·莱杰 Heath Ledger / 杰克·吉伦哈尔 Jake...", "\n                            2005 / 美国 加拿大 / 剧情 爱情 同性 家庭\n                        "]}
{"describe": "幸福是生生不息，却难以触及的远。 ", "name": "萤火虫之墓", "director_and_player": ["\n                            导演: 高畑勋 Isao Takahata   主演: 辰己努 / 白石绫乃 / 志乃原良子", "\n                            1988 / 日本 / 动画 剧情 战争\n                        "]}
{"describe": "九年后的重逢是世俗和责任的交叠，没了悸动和青涩，沧桑而温暖。", "name": "爱在日落黄昏时", "director_and_player": ["\n                            导演: 理查德·林克莱特 Richard Linklater   主演: 伊桑·霍克 Ethan Hawke ...", "\n                            2004 / 美国 / 剧情 爱情\n                        "]}
{"describe": "死可能是一道门，逝去并不是终结，而是超越，走向下一程。", "name": "入殓师", "director_and_player": ["\n                            导演: 泷田洋二郎 Yôjirô Takita   主演: 本木雅弘 Masahiro Motoki / ...", "\n                            2008 / 日本 / 剧情\n                        "]}
{"describe": "在时间之河里感受溺水之苦。", "name": "本杰明·巴顿奇事", "director_and_player": ["\n                            导演: 大卫·芬奇 David Fincher   主演: 凯特·布兰切特 Cate Blanchett / ...", "\n                            2008 / 美国 / 剧情 爱情 奇幻\n                        "]}
{"describe": "安东尼·霍普金斯的顶级表演。", "name": "沉默的羔羊", "director_and_player": ["\n                            导演: Jonathan Demme   主演: Jodie Foster / Anthony Hopkins / Scott Glenn", "\n                            1991 / 美国 / 剧情 犯罪 惊悚\n                        "]}
{"describe": "人的命运被自己瞬间的抉择改变。", "name": "蝴蝶效应", "director_and_player": ["\n                            导演: 埃里克·布雷斯 Eric Bress / J·麦基·格鲁伯 J. Mackye Gruber   主...", "\n                            2004 / 美国 加拿大 / 剧情 悬疑 科幻 惊悚\n                        "]}
{"describe": "爱是一种力量，让我们超越时空感知它的存在。", "name": "星际穿越", "director_and_player": ["\n                            导演: 克里斯托弗·诺兰 Christopher Nolan   主演: 马修·麦康纳 Matthew Mc...", "\n                            2014 / 美国 英国 加拿大 / 剧情 科幻 悬疑 冒险 家庭\n                        "]}
{"describe": "自由万岁。", "name": "飞越疯人院", "director_and_player": ["\n                            导演: 米洛斯·福尔曼 Miloš Forman   主演: 杰克·尼科尔森 Jack Nichols...", "\n                            1975 / 美国 / 剧情\n                        "]}
{"describe": "张艺谋最好的电影。", "name": "活着", "director_and_player": ["\n                            导演: 张艺谋 Yimou Zhang   主演: 葛优 You Ge / 巩俐 Li Gong / 姜武 Wu Jiang", "\n                            1994 / 中国大陆 香港 / 剧情 家庭\n                        "]}
{"describe": "别样人生。", "name": "窃听风暴", "director_and_player": ["\n                            导演: 弗洛里安·亨克尔·冯·多纳斯马 Florian Henckel von Donnersmarck   ...", "\n                            2006 / 德国 / 剧情 悬疑\n                        "]}
{"describe": "海豚的微笑，是世界上最高明的伪装。", "name": "海豚湾", "director_and_player": ["\n                            导演: Louie Psihoyos   主演: John Chisholm / Mandy-Rae Cruikshank / Char...", "\n                            2009 / 美国 / 纪录片\n                        "]}
{"describe": "视觉革命。", "name": "黑客帝国", "director_and_player": ["\n                            导演: 安迪·沃卓斯基 Andy Wachowski / 拉娜·沃卓斯基 Lana Wachowski   主...", "\n                            1999 / 美国 澳大利亚 / 动作 科幻\n                        "]}
{"describe": "美利坚精神输出大片No1.", "name": "拯救大兵瑞恩", "director_and_player": ["\n                            导演: 史蒂文·斯皮尔伯格 Steven Spielberg   主演: 汤姆·汉克斯 Tom Hanks...", "\n                            1998 / 美国 / 剧情 历史 战争\n                        "]}
{"describe": "你是我最好的朋友，你是我唯一的朋友 。", "name": "玛丽和马克思", "director_and_player": ["\n                            导演: Adam Elliot   主演: 托妮·科莱特 Toni Collette / 菲利普·塞默·霍...", "\n                            2009 / 澳大利亚 / 剧情 爱情 动画\n                        "]}
{"describe": "美丽无罪。", "name": "西西里的美丽传说", "director_and_player": ["\n                            导演: 朱塞佩·托纳多雷 Giuseppe Tornatore   主演: 莫妮卡·贝鲁奇 Monica ...", "\n                            2000 / 意大利 美国 / 剧情 战争 情色\n                        "]}
{"describe": "受过伤害的人总是笑得最开心，因为他们不愿意让身边的人承受一样的痛苦。", "name": "素媛", "director_and_player": ["\n                            导演: 李濬益 Jun-ik Lee   主演: 薛景求 Kyung-gu Sol / 严志媛 Ji-won Uhm ...", "\n                            2013 / 韩国 / 剧情 家庭\n                        "]}
{"describe": "史上最美的探戈。", "name": "闻香识女人", "director_and_player": ["\n                            导演: 马丁·布莱斯 Martin Brest   主演: 阿尔·帕西诺 Al Pacino / 克里斯...", "\n                            1992 / 美国 / 剧情\n                        "]}
{"describe": "一张面具背后的理想与革命。", "name": "V字仇杀队", "director_and_player": ["\n                            导演: 詹姆斯·麦克特格 James McTeigue   主演: 娜塔丽·波曼 Natalie Portm...", "\n                            2005 / 美国 英国 德国 / 剧情 动作 科幻 惊悚\n                        "]}
{"describe": "爱是一切逻辑和原由。", "name": "美丽心灵", "director_and_player": ["\n                            导演: 朗·霍华德 Ron Howard   主演: 罗素·克劳 Russell Crowe / 詹妮弗·...", "\n                            2001 / 美国 / 传记 剧情\n                        "]}
{"describe": "优雅的孤独。", "name": "教父2", "director_and_player": ["\n                            导演: 弗朗西斯·福特·科波拉 Francis Ford Coppola   主演: 阿尔·帕西诺 A...", "\n                            1974 / 美国 / 剧情 犯罪\n                        "]}
{"describe": "人生中应该拥有这样的一段豁然开朗。", "name": "心灵捕手", "director_and_player": ["\n                            导演: 格斯·范·桑特 Gus Van Sant   主演: 马特·达蒙 Matt Damon / 罗宾·...", "\n                            1997 / 美国 / 剧情\n                        "]}
{"describe": "带着心爱的人在天空飞翔。", "name": "哈尔的移动城堡", "director_and_player": ["\n                            导演: 宫崎骏 Hayao Miyazaki   主演: 倍赏千惠子 Chieko Baishô / 木村拓...", "\n                            2004 / 日本 / 爱情 动画 奇幻 冒险\n                        "]}
{"describe": "承前启后的史诗篇章。", "name": "指环王2：双塔奇兵", "director_and_player": ["\n                            导演: 彼得·杰克逊 Peter Jackson   主演: 伊利亚·伍德 Elijah Wood / 西恩...", "\n                            2002 / 美国 新西兰 / 剧情 动作 奇幻 冒险\n                        "]}
{"describe": "传说的开始。", "name": "指环王1：魔戒再现", "director_and_player": ["\n                            导演: 彼得·杰克逊 Peter Jackson   主演: 伊利亚·伍德 Elijah Wood / 西恩...", "\n                            2001 / 新西兰 美国 / 剧情 动作 奇幻 冒险\n                        "]}
{"describe": "法式小清新。 ", "name": "天使爱美丽", "director_and_player": ["\n                            导演: Jean-Pierre Jeunet   主演: 奥黛丽·塔图 Audrey Tautou / 马修·卡索...", "\n                            2001 / 法国 德国 / 喜剧 爱情\n                        "]}
{"describe": "暗恋的极致。", "name": "情书", "director_and_player": ["\n                            导演: 岩井俊二 Shunji Iwai   主演: 中山美穗 Miho Nakayama / 丰川悦司 Ets...", "\n                            1995 / 日本 / 剧情 爱情\n                        "]}
